name: vscode-lean build

on: [push, pull_request]

jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run compile
      - run: npm run package
      - uses: actions/upload-artifact@v2
        with:
          name: vscode-lean
          path: 'lean-*.vsix'
